name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}
        source: "."
        target: "/home/bridge/public_html"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}
        script: "chmod 777 -R /home/bridge/public_html/storage && chmod 777 -R /home/bridge/public_html/public && rm -R /home/bridge/public_html/.git && chown -R www-data:www-data /home/bridge/public_html/storage /home/bridge/public_html/public/storage"
